version: "3"

services:
    postgres:
        container_name: hackathonPostgresdb
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: hackathon
            POSTGRES_USER: hackathon
            POSTGRES_PASSWORD: hackathon
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
            interval: 10s
            timeout: 5s
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - hackathonNetwork
    api:
        container_name: hackathonApi
        build: "."
        working_dir: /hackathon
        environment:
            NODE_ENV: development
            POSTGRES_DB: hackathon
            POSTGRES_DB_HOST: postgres
            POSTGRES_DB_PORT: 5432
            POSTGRES_DB_USER: hackathon
            POSTGRES_DB_PASSWORD: hackathon
        command: sh -c "npm run start"
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - "6001:6001"
        networks:
            - hackathonNetwork
networks:
    hackathonNetwork:
        driver: bridge

volumes:
    pgdata:

